import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import 'leaflet/dist/leaflet.css';

const merriweather = Merriweather({
  subsets: ['latin'],
  weight: ['300', '400', '700', '900'], 
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Clackamas Website",
  description: "Generated by React, Leaflet, Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={merriweather.className}>
      <body
      >
        {children}
      </body>
    </html>
  );
}